=== steveloughran/smartfrog/trunk/unmaintained/extras/avalanche/AvalancheGUI/web/tests/testsetup.dtd
<!ELEMENT credentials (#PCDATA)>
<!ATTLIST credentials
        username CDATA #REQUIRED
        password CDATA #REQUIRED>

<!ELEMENT basic (#PCDATA)>
<!ATTLIST basic
        os CDATA #REQUIRED
        vendor CDATA #REQUIRED
        arch CDATA #REQUIRED>

<!ELEMENT environment (#PCDATA)>
<!ATTLIST environment
        name CDATA #REQUIRED
        value CDATA #REQUIRED>

<!ELEMENT host (basic, credentials, environment+) >
<!ATTLIST host
        name CDATA #REQUIRED
        use CDATA #REQUIRED>

<!ELEMENT testsetup (host)*>

=== steveloughran/smartfrog/trunk/unmaintained/extras/avalanche/AvalancheGUI/web/tests/testsetup.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE testsetup SYSTEM "testsetup.dtd" >
<testsetup>
    <host name="host1" use="false">
        <basic os="linux" vendor="Intel" arch="IA64" />
        <credentials username="root" password="xyz" />
        <environment name="AVALANCHE_HOME" value="/tmp" />
        <environment name="JAVA_HOME" value="/usr/java/jdk1.6.0_01" />
    </host>
    <host name="host2" use="true">
        <basic os="linux" vendor="Intel" arch="x86" />
        <credentials username="root" password="xyz" />
        <environment name="AVALANCHE_HOME" value="/tmp" />
        <environment name="JAVA_HOME" value="/usr/java/jdk1.6.0_01" />
    </host>
</testsetup>
